{
	"id": "oval:org.debian:def:259498540314747491704377815667199595690",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2021-28363 python-urllib3",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 12",
			"product": "python-urllib3"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2021-28363",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28363"
			}
		],
		"description": "The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate validation in some cases involving HTTPS to HTTPS proxies. The initial connection to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify the hostname of the certificate. This means certificates for different servers that still validate properly with the default urllib3 SSLContext will be silently accepted.",
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:20467",
								"comment": "python-urllib3 DPKG is earlier than 1.26.4-1"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 12 is installed"
			}
		]
	}
}
