{
  "id": "oval:org.debian:def:302205530106254128455455464448735145860",
  "class": "vulnerability",
  "metadata": {
    "title": "CVE-2019-16224 py-lmdb",
    "affected": {
      "family": "unix",
      "platform": "Debian GNU/Linux 11",
      "product": "py-lmdb"
    },
    "reference": [
      {
        "source": "CVE",
        "ref_id": "CVE-2019-16224",
        "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16224"
      }
    ],
    "description": "An issue was discovered in py-lmdb 0.97. For certain values of md_flags, mdb_node_add does not properly set up a memcpy destination, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
    "debian": {}
  },
  "criteria": {
    "operator": "AND",
    "criterias": [
      {
        "operator": "OR",
        "criterias": [
          {
            "operator": "AND",
            "criterions": [
              {
                "test_ref": "oval:org.debian.oval:tst:2",
                "comment": "all architecture"
              },
              {
                "test_ref": "oval:org.debian.oval:tst:16576",
                "comment": "py-lmdb DPKG is earlier than 0"
              }
            ]
          }
        ]
      }
    ],
    "criterions": [
      {
        "test_ref": "oval:org.debian.oval:tst:1",
        "comment": "Debian 11 is installed"
      }
    ]
  }
}
