{
  "id": "oval:org.debian:def:95167476805247817546582028210513597684",
  "class": "vulnerability",
  "metadata": {
    "title": "CVE-2014-0481 python-django",
    "affected": {
      "family": "unix",
      "platform": "Debian GNU/Linux 11",
      "product": "python-django"
    },
    "reference": [
      {
        "source": "CVE",
        "ref_id": "CVE-2014-0481",
        "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0481"
      }
    ],
    "description": "The default configuration for the file upload handling system in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 uses a sequential file name generation process when a file with a conflicting name is uploaded, which allows remote attackers to cause a denial of service (CPU consumption) by unloading a multiple files with the same name.",
    "debian": {}
  },
  "criteria": {
    "operator": "AND",
    "criterias": [
      {
        "operator": "OR",
        "criterias": [
          {
            "operator": "AND",
            "criterions": [
              {
                "test_ref": "oval:org.debian.oval:tst:2",
                "comment": "all architecture"
              },
              {
                "test_ref": "oval:org.debian.oval:tst:6431",
                "comment": "python-django DPKG is earlier than 1.6.6-1"
              }
            ]
          }
        ]
      }
    ],
    "criterions": [
      {
        "test_ref": "oval:org.debian.oval:tst:1",
        "comment": "Debian 11 is installed"
      }
    ]
  }
}
