{
	"id": "oval:org.debian:def:185263374555653074343387610290547040391",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2019-16228 py-lmdb",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 11",
			"product": "py-lmdb"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2019-16228",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16228"
			}
		],
		"description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:16549",
								"comment": "py-lmdb DPKG is earlier than 0"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 11 is installed"
			}
		]
	}
}
