{
	"id": "oval:org.debian:def:21707817840629986291314493445628946290",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2022-48565 pypy3",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 11",
			"product": "pypy3"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2022-48565",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-48565"
			}
		],
		"description": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:26473",
								"comment": "pypy3 DPKG is earlier than 7.3.5+dfsg-2"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 11 is installed"
			}
		]
	}
}
