{
	"id": "oval:org.debian:def:293061400995834922108744173112872543416",
	"class": "patch",
	"metadata": {
		"title": "DSA-4161-1 python-django",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 8",
			"product": "python-django"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2018-7536",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-7536"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2018-7537",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-7537"
			}
		],
		"description": "security update",
		"debian": {
			"moreinfo": "no info",
			"dsa": "DSA-4161",
			"date": "2018-04-01"
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:3486",
								"comment": "python-django DPKG is earlier than 1.7.11-1+deb8u3"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 8 is installed"
			}
		]
	}
}
