{
  "id": "oval:org.debian:def:34053100898814347553811654166620087830",
  "class": "patch",
  "metadata": {
    "title": "DSA-3544-1 python-django",
    "affected": {
      "family": "unix",
      "platform": "Debian GNU/Linux 8",
      "product": "python-django"
    },
    "reference": [
      {
        "source": "CVE",
        "ref_id": "CVE-2016-2512",
        "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-2512"
      },
      {
        "source": "CVE",
        "ref_id": "CVE-2016-2513",
        "ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-2513"
      }
    ],
    "description": "security update",
    "debian": {
      "moreinfo": "\nSeveral vulnerabilities were discovered in Django, a high-level Python web development framework. The Common Vulnerabilities and Exposures project identifies the following problems:",
      "dsa": "DSA-3544",
      "date": "2016-04-07"
    }
  },
  "criteria": {
    "operator": "AND",
    "criterias": [
      {
        "operator": "OR",
        "criterias": [
          {
            "operator": "AND",
            "criterions": [
              {
                "test_ref": "oval:org.debian.oval:tst:2",
                "comment": "all architecture"
              },
              {
                "test_ref": "oval:org.debian.oval:tst:1714",
                "comment": "python-django DPKG is earlier than 1.7.7-1+deb8u4"
              }
            ]
          }
        ]
      }
    ],
    "criterions": [
      {
        "test_ref": "oval:org.debian.oval:tst:1",
        "comment": "Debian 8 is installed"
      }
    ]
  }
}
