{
	"id": "oval:org.debian:def:248040479224020352369722069044278562460",
	"class": "patch",
	"metadata": {
		"title": "DSA-4498-1 python-django",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 9",
			"product": "python-django"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2019-14232",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14232"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2019-14233",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14233"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2019-14234",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14234"
			},
			{
				"source": "CVE",
				"ref_id": "CVE-2019-14235",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14235"
			}
		],
		"description": "security update",
		"debian": {
			"moreinfo": "\nSeveral vulnerabilities were discovered in python-django, a web development framework. They could lead to remote denial-of-service or SQL injection,",
			"dsa": "DSA-4498",
			"date": "2019-08-12"
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:3046",
								"comment": "python-django DPKG is earlier than 1:1.10.7-2+deb9u6"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 9 is installed"
			}
		]
	}
}
