{
	"id": "oval:org.debian:def:126399310440102263905717965777151577894",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2019-9948 python3.7",
		"affected": {
			"family": "unix",
			"platform": "Debian GNU/Linux 10",
			"product": "python3.7"
		},
		"reference": [
			{
				"source": "CVE",
				"ref_id": "CVE-2019-9948",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-9948"
			}
		],
		"description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
		"debian": {}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterias": [
					{
						"operator": "AND",
						"criterions": [
							{
								"test_ref": "oval:org.debian.oval:tst:2",
								"comment": "all architecture"
							},
							{
								"test_ref": "oval:org.debian.oval:tst:18173",
								"comment": "python3.7 DPKG is earlier than 3.7.3-2+deb10u1"
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.debian.oval:tst:1",
				"comment": "Debian 10 is installed"
			}
		]
	}
}
